package com.sugr.examples.sqlclient;

import com.sugr.bridge.Json;
import com.sugr.core.Application;
import com.sugr.core.Frontend;

import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicReference;

/**
 * Example app for the sugr core/bridge library: a tiny SQLite client.
 * Everything below the builder is app-specific glue (SqlBridge, JSON shaping)
 * - the library itself only knows about Application/Frontend/Bridge.
 */
public final class Main {

    public static void main(String[] args) throws Throwable {
        SqlBridge sqlBridge = new SqlBridge();
        // Generated by the @Bind annotation processor from SqlBridge: connect(),
        // listTables(), slowGreet() - see SqlBridgeBridge in build/generated/sources.
        SqlBridgeBridge generatedBridge = new SqlBridgeBridge(sqlBridge);
        // Handlers below need to call app.emit(...), but the Application instance
        // only exists once the builder finishes - stash it via onReady().
        AtomicReference<Application> appRef = new AtomicReference<>();

        Application.Builder builder = Application.builder()
                .title("sugr - SQL client")
                .size(1000, 700)
                .frontend(devServerUrlFromEnv() != null
                        ? Frontend.devServer(devServerUrlFromEnv())
                        : Frontend.embedded("/frontend"))
                // Hand-written: still emits a "query-executed" event as a side effect,
                // which @Bind doesn't (and shouldn't) know how to generate.
                .bind("query", params -> {
                    List<String> a = Json.parseStringArray(params);
                    if (a.isEmpty() || a.get(0) == null) {
                        throw new IllegalArgumentException("query requires a SQL string argument");
                    }
                    List<Map<String, String>> rows = sqlBridge.query(a.get(0));
                    Application app = appRef.get();
                    if (app != null) {
                        app.emit("query-executed", Json.quote(rows.size() + " row(s)"));
                    }
                    return rowsToJson(rows);
                })
                .on("ping", payload -> {
                    Application app = appRef.get();
                    if (app != null) {
                        app.emit("pong", Json.quote("pong! (Java received: " + payload + ")"));
                    }
                })
                .onReady(appRef::set);

        generatedBridge.bindTo(builder);
        builder.run();

        sqlBridge.close();
    }

    private static String rowsToJson(List<Map<String, String>> rows) {
        StringBuilder json = new StringBuilder("[");
        for (int i = 0; i < rows.size(); i++) {
            if (i > 0) json.append(',');
            json.append('{');
            int j = 0;
            for (Map.Entry<String, String> col : rows.get(i).entrySet()) {
                if (j++ > 0) json.append(',');
                json.append(Json.quote(col.getKey())).append(':').append(Json.quote(col.getValue()));
            }
            json.append('}');
        }
        return json.append(']').toString();
    }

    private static String devServerUrlFromEnv() {
        String url = System.getenv("SUGR_DEV_URL");
        return (url == null || url.isBlank()) ? null : url;
    }
}
