import { useEffect, useState } from 'react'
import { invoke, events, type BridgeError } from '@sugr/runtime'
import { SqlBridge } from './generated/SqlBridge.generated'
import './App.css'

type Row = Record<string, string | null>

const DEFAULT_SQL =
  "CREATE TABLE users(id INTEGER PRIMARY KEY, name TEXT, age INTEGER);\n" +
  "INSERT INTO users(name, age) VALUES ('Alice', 30), ('Bob', 25);\n" +
  'SELECT * FROM users;'

function App() {
  const [status, setStatus] = useState('not connected')
  const [sql, setSql] = useState(DEFAULT_SQL)
  const [rows, setRows] = useState<Row[]>([])
  const [tables, setTables] = useState<string[]>([])
  const [error, setError] = useState<string | null>(null)
  const [lastEvent, setLastEvent] = useState<string | null>(null)
  const [pong, setPong] = useState<string | null>(null)
  const [greeting, setGreeting] = useState<string | null>(null)
  const [dbPath, setDbPath] = useState<string | null>(null)
  const [clipboardText, setClipboardText] = useState('hello from sugr')

  useEffect(() => {
    // Java -> JS: Main.java emits this after every successful query.
    events.on<string>('query-executed', (payload) => setLastEvent(payload))
    // Java -> JS: reply to the "ping" event emitted below.
    events.on<string>('pong', (payload) => setPong(payload))
  }, [])

  async function handleConnect() {
    setError(null)
    try {
      // SqlBridge.connect is generated by @Bind from SqlBridge.java - typed, no invoke() call written by hand.
      const message = await SqlBridge.connect(':memory:')
      setStatus(message)
    } catch (e) {
      setError(String(e))
    }
  }

  async function handleRunQuery() {
    setError(null)
    try {
      // "query" stays hand-written on the Java side (it also emits an event), called via raw invoke().
      const result = await invoke<Row[]>('query', [sql])
      setRows(result)
    } catch (e) {
      setError(String(e))
      setRows([])
    }
  }

  async function handleListTables() {
    setError(null)
    try {
      const result = await SqlBridge.listTables()
      setTables(result)
    } catch (e) {
      setError(String(e))
    }
  }

  async function handleSlowGreet() {
    setError(null)
    try {
      // CompletableFuture<String> completed from a background thread on the Java
      // side (see SqlBridge.slowGreet) - resolves the Promise correctly.
      const result = await SqlBridge.slowGreet('sugr')
      setGreeting(result)
    } catch (e) {
      setError(String(e))
    }
  }

  function handlePing() {
    events.emit('ping', { from: 'react', at: Date.now() })
  }

  async function handlePickFile() {
    setError(null)
    try {
      // Native "open file" dialog (core.Dialogs) - see pickDatabaseFile's javadoc.
      const path = await SqlBridge.pickDatabaseFile()
      setDbPath(path)
    } catch (e) {
      // Structured error (com.sugr.bridge.BridgeException) - check `code` instead
      // of parsing message text to tell "cancelled" apart from a real failure.
      const err = e as BridgeError
      if (err.code === 'DIALOG_CANCELLED') {
        setDbPath(null)
      } else {
        setError(err.message ?? String(e))
      }
    }
  }

  async function handleCopyToClipboard() {
    setError(null)
    try {
      await SqlBridge.copyToClipboard(clipboardText)
    } catch (e) {
      setError(String(e))
    }
  }

  const columns = rows.length > 0 ? Object.keys(rows[0]) : []

  return (
    <section id="sql-client" style={{ padding: '1.5rem', fontFamily: 'sans-serif' }}>
      <h1>sugr - SQL client (@Bind codegen demo)</h1>
      <p>Status: {status}</p>
      {lastEvent && <p>Last event from Java: {lastEvent}</p>}

      <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '1rem', flexWrap: 'wrap' }}>
        <button type="button" onClick={handleConnect}>Connect (:memory:)</button>
        <button type="button" onClick={handleListTables}>List tables</button>
        <button type="button" onClick={handlePing}>Emit ping event</button>
        <button type="button" onClick={handleSlowGreet}>slowGreet() (CompletableFuture)</button>
        <button type="button" onClick={handlePickFile}>Pick a file (native dialog)</button>
      </div>

      {pong && <p>Reply to ping: {pong}</p>}
      {greeting && <p>slowGreet result: {greeting}</p>}
      {dbPath && <p>Picked file: {dbPath}</p>}

      <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center', marginBottom: '1rem' }}>
        <input
          value={clipboardText}
          onChange={(e) => setClipboardText(e.target.value)}
          style={{ fontFamily: 'monospace' }}
        />
        <button type="button" onClick={handleCopyToClipboard}>Copy to clipboard</button>
      </div>

      <textarea
        value={sql}
        onChange={(e) => setSql(e.target.value)}
        rows={6}
        style={{ width: '100%', maxWidth: '640px', fontFamily: 'monospace' }}
      />
      <div style={{ marginTop: '0.5rem' }}>
        <button type="button" onClick={handleRunQuery}>Run query</button>
      </div>

      {error && <p style={{ color: 'crimson' }}>Error: {error}</p>}

      {tables.length > 0 && (
        <p>Tables: {tables.join(', ')}</p>
      )}

      {rows.length > 0 && (
        <table border={1} cellPadding={4} style={{ marginTop: '1rem', borderCollapse: 'collapse' }}>
          <thead>
            <tr>
              {columns.map((col) => (
                <th key={col}>{col}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map((row, i) => (
              <tr key={i}>
                {columns.map((col) => (
                  <td key={col}>{row[col] ?? 'NULL'}</td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </section>
  )
}

export default App
