package com.sugr.bridge;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Minimal hand-written JSON value model: parse, build, and encode - no
 * Jackson databind, per plan.md. Used both by hand-written binds (via the
 * {@link #quote} / {@link #parseStringArray} convenience methods) and by
 * code generated by the {@code processor} module (records, List/Map, numbers).
 */
public sealed interface Json {

    record Str(String value) implements Json {
    }

    record Num(double value) implements Json {
    }

    record Bool(boolean value) implements Json {
    }

    record Null() implements Json {
    }

    record Arr(List<Json> items) implements Json {
    }

    record Obj(Map<String, Json> fields) implements Json {
    }

    Json NULL = new Null();

    static Json of(String s) {
        return s == null ? NULL : new Str(s);
    }

    static Json of(double d) {
        return new Num(d);
    }

    static Json of(long l) {
        return new Num(l);
    }

    static Json of(boolean b) {
        return new Bool(b);
    }

    static Json array(List<Json> items) {
        return new Arr(items);
    }

    static Json object(Map<String, Json> fields) {
        return new Obj(fields);
    }

    static Json parse(String text) {
        Parser p = new Parser(text);
        Json value = p.parseValue();
        p.skipWs();
        if (!p.atEnd()) {
            throw new IllegalArgumentException("Trailing content in JSON: " + text);
        }
        return value;
    }

    /** Shorthand for {@code Json.of(s).encode()} - a JSON string literal, e.g. "hi" -> "\"hi\"". */
    static String quote(String s) {
        return of(s).encode();
    }

    /** Parses a JSON array containing only strings (or null), e.g. ["a","b"] or []. */
    static List<String> parseStringArray(String text) {
        List<Json> items = parse(text).asArray();
        List<String> out = new ArrayList<>(items.size());
        for (Json item : items) {
            out.add(item.isNull() ? null : item.asString());
        }
        return out;
    }

    default String asString() {
        if (this instanceof Str s) {
            return s.value();
        }
        throw new IllegalStateException("Not a JSON string: " + encode());
    }

    default double asNumber() {
        if (this instanceof Num n) {
            return n.value();
        }
        throw new IllegalStateException("Not a JSON number: " + encode());
    }

    default boolean asBoolean() {
        if (this instanceof Bool b) {
            return b.value();
        }
        throw new IllegalStateException("Not a JSON boolean: " + encode());
    }

    default boolean isNull() {
        return this instanceof Null;
    }

    default List<Json> asArray() {
        if (this instanceof Arr a) {
            return a.items();
        }
        throw new IllegalStateException("Not a JSON array: " + encode());
    }

    default Map<String, Json> asObject() {
        if (this instanceof Obj o) {
            return o.fields();
        }
        throw new IllegalStateException("Not a JSON object: " + encode());
    }

    default String encode() {
        StringBuilder out = new StringBuilder();
        encodeInto(out);
        return out.toString();
    }

    private void encodeInto(StringBuilder out) {
        switch (this) {
            case Str s -> {
                out.append('"');
                escape(s.value(), out);
                out.append('"');
            }
            case Num n -> {
                double d = n.value();
                if (d == Math.rint(d) && !Double.isInfinite(d) && Math.abs(d) < 1e15) {
                    out.append((long) d);
                } else {
                    out.append(d);
                }
            }
            case Bool b -> out.append(b.value());
            case Null ignored -> out.append("null");
            case Arr a -> {
                out.append('[');
                List<Json> items = a.items();
                for (int i = 0; i < items.size(); i++) {
                    if (i > 0) out.append(',');
                    items.get(i).encodeInto(out);
                }
                out.append(']');
            }
            case Obj o -> {
                out.append('{');
                boolean first = true;
                for (Map.Entry<String, Json> e : o.fields().entrySet()) {
                    if (!first) out.append(',');
                    first = false;
                    out.append('"');
                    escape(e.getKey(), out);
                    out.append('"').append(':');
                    e.getValue().encodeInto(out);
                }
                out.append('}');
            }
        }
    }

    private static void escape(String s, StringBuilder out) {
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            switch (c) {
                case '"' -> out.append("\\\"");
                case '\\' -> out.append("\\\\");
                case '\n' -> out.append("\\n");
                case '\r' -> out.append("\\r");
                case '\t' -> out.append("\\t");
                default -> {
                    if (c < 0x20) {
                        out.append(String.format("\\u%04x", (int) c));
                    } else {
                        out.append(c);
                    }
                }
            }
        }
    }

    final class Parser {
        private final String text;
        private int pos;

        Parser(String text) {
            this.text = text;
        }

        boolean atEnd() {
            return pos >= text.length();
        }

        void skipWs() {
            while (pos < text.length() && Character.isWhitespace(text.charAt(pos))) {
                pos++;
            }
        }

        Json parseValue() {
            skipWs();
            if (atEnd()) {
                throw new IllegalArgumentException("Unexpected end of JSON");
            }
            char c = text.charAt(pos);
            return switch (c) {
                case '"' -> parseString();
                case '{' -> parseObject();
                case '[' -> parseArray();
                case 't' -> {
                    expect("true");
                    yield new Bool(true);
                }
                case 'f' -> {
                    expect("false");
                    yield new Bool(false);
                }
                case 'n' -> {
                    expect("null");
                    yield NULL;
                }
                default -> parseNumber();
            };
        }

        private void expect(String literal) {
            if (!text.startsWith(literal, pos)) {
                throw new IllegalArgumentException("Expected " + literal + " at " + pos);
            }
            pos += literal.length();
        }

        private Str parseString() {
            pos++; // opening quote
            StringBuilder sb = new StringBuilder();
            while (text.charAt(pos) != '"') {
                char c = text.charAt(pos);
                if (c == '\\') {
                    pos++;
                    char esc = text.charAt(pos);
                    switch (esc) {
                        case 'n' -> sb.append('\n');
                        case 'r' -> sb.append('\r');
                        case 't' -> sb.append('\t');
                        case 'b' -> sb.append('\b');
                        case 'f' -> sb.append('\f');
                        case '"' -> sb.append('"');
                        case '\\' -> sb.append('\\');
                        case '/' -> sb.append('/');
                        case 'u' -> {
                            String hex = text.substring(pos + 1, pos + 5);
                            sb.append((char) Integer.parseInt(hex, 16));
                            pos += 4;
                        }
                        default -> sb.append(esc);
                    }
                } else {
                    sb.append(c);
                }
                pos++;
            }
            pos++; // closing quote
            return new Str(sb.toString());
        }

        private Num parseNumber() {
            int start = pos;
            if (text.charAt(pos) == '-') pos++;
            while (pos < text.length() && (Character.isDigit(text.charAt(pos)) || text.charAt(pos) == '.'
                    || text.charAt(pos) == 'e' || text.charAt(pos) == 'E'
                    || text.charAt(pos) == '+' || text.charAt(pos) == '-')) {
                pos++;
            }
            return new Num(Double.parseDouble(text.substring(start, pos)));
        }

        private Arr parseArray() {
            pos++; // [
            List<Json> items = new ArrayList<>();
            skipWs();
            if (text.charAt(pos) == ']') {
                pos++;
                return new Arr(items);
            }
            while (true) {
                items.add(parseValue());
                skipWs();
                char c = text.charAt(pos);
                if (c == ',') {
                    pos++;
                    continue;
                }
                if (c == ']') {
                    pos++;
                    break;
                }
                throw new IllegalArgumentException("Expected , or ] at " + pos);
            }
            return new Arr(items);
        }

        private Obj parseObject() {
            pos++; // {
            Map<String, Json> fields = new LinkedHashMap<>();
            skipWs();
            if (text.charAt(pos) == '}') {
                pos++;
                return new Obj(fields);
            }
            while (true) {
                skipWs();
                Str key = parseString();
                skipWs();
                if (text.charAt(pos) != ':') {
                    throw new IllegalArgumentException("Expected : at " + pos);
                }
                pos++;
                Json value = parseValue();
                fields.put(key.value(), value);
                skipWs();
                char c = text.charAt(pos);
                if (c == ',') {
                    pos++;
                    continue;
                }
                if (c == '}') {
                    pos++;
                    break;
                }
                throw new IllegalArgumentException("Expected , or } at " + pos);
            }
            return new Obj(fields);
        }
    }
}
