package app.__pkg__;

import com.sugr.core.AppConfig;
import com.sugr.core.Application;
import com.sugr.core.Frontend;

/**
 * Generated by `sugr init`. Backend.java's @Bind methods are wired in below
 * via the processor-generated BackendBridge - see plan.md Giai đoạn 3 for how
 * that works, or examples/sql-client for a fuller app.
 */
public final class Main {

    public static void main(String[] args) throws Throwable {
        // application.properties + application-<env>.properties (env from SUGR_ENV,
        // defaulting to "prod") - see docs/guide/environments.md.
        AppConfig config = AppConfig.load("SUGR_ENV", "prod");

        Backend backend = new Backend();
        BackendBridge generatedBridge = new BackendBridge(backend);

        Application.Builder builder = Application.builder()
                .title(config.getOrDefault("app.name", "__APP_NAME__"))
                .size(900, 640)
                .frontend(Frontend.auto());

        generatedBridge.bindTo(builder);
        builder.run();
    }
}
