package com.sugr.cli;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Figures out, from the app directory the CLI was invoked in, which Gradle
 * task to run. Two cases:
 *
 * <ul>
 *   <li>The app directory itself has a settings.gradle.kts - it's a standalone
 *       build, just run the bare task name ("run", "build") from there.</li>
 *   <li>An ancestor directory has settings.gradle.kts (the app is one module
 *       of a multi-project build - our own examples/sql-client, or any app
 *       generated by a future `sugr init` that gets folded into a monorepo) -
 *       parse it well enough to map the app directory back to a Gradle
 *       project path (e.g. ":examples:sql-client"), so the task becomes
 *       ":examples:sql-client:run" and gradle runs from the ancestor root.</li>
 * </ul>
 *
 * Understands plain {@code include("a", "b:c")} and
 * {@code project(":a:b").projectDir = file("...")} overrides - the two forms
 * our own settings.gradle.kts (and most simple multi-project builds) use.
 * Anything fancier (dynamic settings logic, included builds) won't resolve -
 * callers should fall back to asking the user for an explicit --task.
 */
final class GradleProjectLocator {

    record Result(Path gradleDir, String task) {
    }

    private GradleProjectLocator() {
    }

    /**
     * Shared by {@link DevCommand} and {@link BuildCommand}: honors explicit
     * {@code --task}/{@code --gradle-dir} overrides if either is given, otherwise
     * auto-detects via {@link #locate}. Throws with a user-facing message on failure.
     *
     * @param bareTask the task name to fall back to for a standalone build or an
     *                  explicit {@code --gradle-dir} without {@code --task}, e.g. "run" or "build"
     */
    static Result resolve(String taskOverride, String dirOverride, String bareTask) throws IOException {
        if (taskOverride != null || dirOverride != null) {
            String task = taskOverride != null ? taskOverride : bareTask;
            Path dir = dirOverride != null ? Path.of(dirOverride).toAbsolutePath().normalize() : Path.of(".").toAbsolutePath().normalize();
            return new Result(dir, task);
        }
        Result result = locate(Path.of("."), bareTask);
        if (result == null) {
            throw new IOException("[sugr] couldn't find a settings.gradle(.kts) for this directory or any parent - "
                    + "pass --task and --gradle-dir explicitly.");
        }
        return result;
    }

    /** @param bareTask the task name to run for a standalone build, e.g. "run" or "build" */
    static Result locate(Path appDir, String bareTask) throws IOException {
        Path dir = appDir.toAbsolutePath().normalize();

        if (Files.exists(dir.resolve("settings.gradle.kts")) || Files.exists(dir.resolve("settings.gradle"))) {
            return new Result(dir, bareTask);
        }

        Path cursor = dir.getParent();
        while (cursor != null) {
            Path settings = cursor.resolve("settings.gradle.kts");
            if (Files.exists(settings)) {
                Map<Path, String> projects = parseProjectDirs(cursor, settings);
                // Exact match first; then fall back to "dir is an ancestor of the project's
                // directory" - covers the frontend/ + lib/ sibling layout our own examples
                // use, where the app root you `cd` into isn't the Gradle project dir itself.
                String path = projects.get(dir);
                if (path == null) {
                    for (Map.Entry<Path, String> e : projects.entrySet()) {
                        if (e.getKey().startsWith(dir)) {
                            path = e.getValue();
                            break;
                        }
                    }
                }
                if (path != null) {
                    return new Result(cursor, path + ":" + bareTask);
                }
                return null;
            }
            cursor = cursor.getParent();
        }
        return null;
    }

    private static final Pattern INCLUDE = Pattern.compile("include\\(([^)]*)\\)");
    private static final Pattern QUOTED = Pattern.compile("\"([^\"]+)\"");
    private static final Pattern PROJECT_DIR_OVERRIDE = Pattern.compile(
            "project\\(\\s*\"(:[^\"]+)\"\\s*\\)\\s*\\.\\s*projectDir\\s*=\\s*file\\(\\s*\"([^\"]+)\"\\s*\\)");

    /** Maps each declared project's absolute directory to its Gradle path (":a:b"). */
    private static Map<Path, String> parseProjectDirs(Path root, Path settingsFile) throws IOException {
        String content = Files.readString(settingsFile);
        Map<Path, String> result = new LinkedHashMap<>();

        Matcher includeMatcher = INCLUDE.matcher(content);
        while (includeMatcher.find()) {
            Matcher args = QUOTED.matcher(includeMatcher.group(1));
            while (args.find()) {
                String raw = args.group(1); // e.g. "examples:sql-client"
                String gradlePath = ":" + raw;
                String defaultRelativeDir = raw.replace(":", "/");
                result.put(root.resolve(defaultRelativeDir).normalize(), gradlePath);
            }
        }

        Matcher overrideMatcher = PROJECT_DIR_OVERRIDE.matcher(content);
        while (overrideMatcher.find()) {
            String gradlePath = overrideMatcher.group(1);
            String relativeDir = overrideMatcher.group(2);
            result.entrySet().removeIf(e -> e.getValue().equals(gradlePath));
            result.put(root.resolve(relativeDir).normalize(), gradlePath);
        }

        return result;
    }
}
