package com.sugr.processor;

import com.sugr.bridge.Bind;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import javax.tools.Diagnostic;
import javax.tools.FileObject;
import javax.tools.JavaFileObject;
import javax.tools.StandardLocation;
import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Compile-time processor for {@link Bind}: generates a "&lt;Target&gt;Bridge"
 * dispatcher class (no reflection - direct method calls) plus a typed TS
 * stub file, per plan.md Giai đoạn 3 Milestone 3.1.
 */
@SupportedAnnotationTypes("com.sugr.bridge.Bind")
public final class BindProcessor extends AbstractProcessor {

    @Override
    public SourceVersion getSupportedSourceVersion() {
        return SourceVersion.latestSupported();
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (roundEnv.processingOver()) {
            return false;
        }
        Map<TypeElement, List<ExecutableElement>> byClass = new LinkedHashMap<>();
        for (Element el : roundEnv.getElementsAnnotatedWith(Bind.class)) {
            if (el.getKind() != ElementKind.METHOD) {
                continue;
            }
            ExecutableElement method = (ExecutableElement) el;
            TypeElement owner = (TypeElement) method.getEnclosingElement();
            byClass.computeIfAbsent(owner, k -> new ArrayList<>()).add(method);
        }
        for (Map.Entry<TypeElement, List<ExecutableElement>> entry : byClass.entrySet()) {
            generateBridgeClass(entry.getKey(), entry.getValue());
        }
        return true;
    }

    /**
     * Everything {@link #generateOneBind} and {@link #generateTsStub} need about one
     * @Bind method, computed once - both used to recompute jsName/async/return-type/isVoid
     * independently from the raw {@link ExecutableElement}.
     */
    private record BoundMethod(String jsName, String javaMethodName, List<? extends VariableElement> params,
                                boolean async, TypeMirror returnType, boolean isVoid) {

        static BoundMethod of(ExecutableElement method, TypeCodec codec) {
            Bind bindAnno = method.getAnnotation(Bind.class);
            String jsName = bindAnno.value().isEmpty() ? method.getSimpleName().toString() : bindAnno.value();
            TypeMirror rawReturn = method.getReturnType();
            boolean async = codec.isCompletableFuture(rawReturn);
            TypeMirror returnType = async ? codec.completableFutureInner(rawReturn) : rawReturn;
            boolean isVoid = returnType.getKind() == TypeKind.VOID;
            return new BoundMethod(jsName, method.getSimpleName().toString(), method.getParameters(),
                    async, returnType, isVoid);
        }
    }

    private void generateBridgeClass(TypeElement target, List<ExecutableElement> methods) {
        String pkg = processingEnv.getElementUtils().getPackageOf(target).getQualifiedName().toString();
        String targetSimple = target.getSimpleName().toString();
        String bridgeSimple = targetSimple + "Bridge";
        String bridgeQualified = pkg.isEmpty() ? bridgeSimple : pkg + "." + bridgeSimple;

        TypeCodec codec = new TypeCodec(processingEnv);
        List<BoundMethod> bound = methods.stream().map(m -> BoundMethod.of(m, codec)).toList();

        StringBuilder bindCalls = new StringBuilder();
        for (BoundMethod bm : bound) {
            bindCalls.append(generateOneBind(bm, codec));
        }

        StringBuilder src = new StringBuilder();
        if (!pkg.isEmpty()) {
            src.append("package ").append(pkg).append(";\n\n");
        }
        src.append("/** Generated by sugr's @Bind annotation processor from ")
                .append(targetSimple).append(". Do not edit by hand. */\n");
        src.append("public final class ").append(bridgeSimple).append(" {\n\n");
        src.append("    private final ").append(targetSimple).append(" target;\n\n");
        src.append("    public ").append(bridgeSimple).append('(').append(targetSimple).append(" target) {\n");
        src.append("        this.target = target;\n    }\n\n");
        src.append("    public void bindTo(com.sugr.core.Application.Builder builder) {\n");
        src.append(bindCalls);
        src.append("    }\n\n");
        for (String helper : codec.helperMethodsSource()) {
            src.append("    ").append(helper.replace("\n", "\n    ")).append("\n\n");
        }
        src.append("}\n");

        try {
            JavaFileObject file = processingEnv.getFiler().createSourceFile(bridgeQualified, target);
            try (Writer w = file.openWriter()) {
                w.write(src.toString());
            }
        } catch (IOException e) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                    "Failed to write " + bridgeQualified + ": " + e, target);
        }

        generateTsStub(pkg, targetSimple, bound, codec);
    }

    private String generateOneBind(BoundMethod bm, TypeCodec codec) {
        StringBuilder call = new StringBuilder();
        call.append("        builder.").append(bm.async() ? "bindAsync" : "bind")
                .append("(\"").append(bm.jsName()).append("\", params -> {\n");
        call.append("            java.util.List<com.sugr.bridge.Json> __args = com.sugr.bridge.Json.parse(params).asArray();\n");

        StringBuilder argNames = new StringBuilder();
        List<? extends VariableElement> params = bm.params();
        for (int i = 0; i < params.size(); i++) {
            VariableElement p = params.get(i);
            String argVar = "arg" + i;
            call.append("            ").append(codec.javaTypeName(p.asType())).append(' ').append(argVar)
                    .append(" = ").append(codec.decode(p.asType(), "__args.get(" + i + ")")).append(";\n");
            if (i > 0) argNames.append(", ");
            argNames.append(argVar);
        }

        if (bm.async()) {
            call.append("            return target.").append(bm.javaMethodName()).append('(').append(argNames).append(')');
            if (bm.isVoid()) {
                call.append(".thenApply(__ignored -> \"null\");\n");
            } else {
                call.append(".thenApply(__r -> ").append(codec.encode(bm.returnType(), "__r")).append(".encode());\n");
            }
        } else if (bm.isVoid()) {
            call.append("            target.").append(bm.javaMethodName()).append('(').append(argNames).append(");\n");
            call.append("            return \"null\";\n");
        } else {
            call.append("            ").append(codec.javaTypeName(bm.returnType())).append(" __result = target.")
                    .append(bm.javaMethodName()).append('(').append(argNames).append(");\n");
            call.append("            return ").append(codec.encode(bm.returnType(), "__result")).append(".encode();\n");
        }
        call.append("        });\n");
        return call.toString();
    }

    private void generateTsStub(String pkg, String targetSimple, List<BoundMethod> methods, TypeCodec codec) {
        StringBuilder methodsTs = new StringBuilder();
        for (BoundMethod bm : methods) {
            String tsReturn = bm.isVoid() ? "void" : codec.tsType(bm.returnType());

            StringBuilder paramList = new StringBuilder();
            StringBuilder argArray = new StringBuilder();
            List<? extends VariableElement> params = bm.params();
            for (int i = 0; i < params.size(); i++) {
                VariableElement p = params.get(i);
                String name = p.getSimpleName().toString();
                if (i > 0) {
                    paramList.append(", ");
                    argArray.append(", ");
                }
                paramList.append(name).append(": ").append(codec.tsType(p.asType()));
                argArray.append(name);
            }
            methodsTs.append("  ").append(bm.jsName()).append('(').append(paramList).append("): Promise<").append(tsReturn).append("> {\n");
            methodsTs.append("    return invoke('").append(bm.jsName()).append("', [").append(argArray).append("])\n");
            methodsTs.append("  },\n");
        }

        StringBuilder ts = new StringBuilder();
        ts.append("// AUTO-GENERATED by sugr's @Bind annotation processor from ").append(targetSimple).append(". Do not edit by hand.\n");
        ts.append("import { invoke } from '@sugr/runtime'\n\n");
        for (String iface : codec.tsInterfaceSource().values()) {
            ts.append(iface).append("\n\n");
        }
        ts.append("export const ").append(targetSimple).append(" = {\n").append(methodsTs).append("}\n");

        try {
            String relativeName = targetSimple + ".generated.ts";
            FileObject file = processingEnv.getFiler().createResource(StandardLocation.SOURCE_OUTPUT, pkg, relativeName);
            try (Writer w = file.openWriter()) {
                w.write(ts.toString());
            }
        } catch (IOException e) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, "Failed to write TS stub: " + e);
        }
    }
}
