package com.sugr.processor;

import com.sugr.bridge.Emits;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import javax.lang.model.type.TypeKind;
import javax.tools.Diagnostic;
import javax.tools.FileObject;
import javax.tools.JavaFileObject;
import javax.tools.StandardLocation;
import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Compile-time processor for {@link Emits}: generates a "&lt;Interface&gt;Emitter"
 * class (real {@code Window.emit} calls, no hand-written event-name strings) plus a
 * typed TS stub exposing {@code on<Name>()}/unsubscribe pairs, mirroring
 * {@link BindProcessor} for the opposite (Java -&gt; JS) direction.
 */
@SupportedAnnotationTypes("com.sugr.bridge.Emits")
public final class EmitsProcessor extends AbstractProcessor {

    @Override
    public SourceVersion getSupportedSourceVersion() {
        return SourceVersion.latestSupported();
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (roundEnv.processingOver()) {
            return false;
        }
        Map<TypeElement, List<ExecutableElement>> byInterface = new LinkedHashMap<>();
        for (Element el : roundEnv.getElementsAnnotatedWith(Emits.class)) {
            if (el.getKind() != ElementKind.METHOD) {
                continue;
            }
            ExecutableElement method = (ExecutableElement) el;
            TypeElement owner = (TypeElement) method.getEnclosingElement();
            byInterface.computeIfAbsent(owner, k -> new ArrayList<>()).add(method);
        }
        for (Map.Entry<TypeElement, List<ExecutableElement>> entry : byInterface.entrySet()) {
            generateEmitterClass(entry.getKey(), entry.getValue());
        }
        return true;
    }

    /** Everything the Java and TS generators need about one @Emits method, computed once. */
    private record EmittedEvent(String jsName, String javaMethodName, VariableElement payload) {

        static EmittedEvent of(ExecutableElement method, Messager messager) {
            Emits emitsAnno = method.getAnnotation(Emits.class);
            String jsName = emitsAnno.value().isEmpty() ? method.getSimpleName().toString() : emitsAnno.value();
            List<? extends VariableElement> params = method.getParameters();
            if (params.size() > 1) {
                messager.printMessage(Diagnostic.Kind.ERROR,
                        "@Emits methods take at most one parameter (the event payload) - bundle multiple "
                                + "values into a record instead", method);
            }
            if (method.getReturnType().getKind() != TypeKind.VOID) {
                messager.printMessage(Diagnostic.Kind.ERROR, "@Emits methods must return void", method);
            }
            VariableElement payload = params.isEmpty() ? null : params.get(0);
            return new EmittedEvent(jsName, method.getSimpleName().toString(), payload);
        }
    }

    private interface Messager {
        void printMessage(Diagnostic.Kind kind, String msg, Element el);
    }

    private void generateEmitterClass(TypeElement target, List<ExecutableElement> methods) {
        String pkg = processingEnv.getElementUtils().getPackageOf(target).getQualifiedName().toString();
        String targetSimple = target.getSimpleName().toString();
        String emitterSimple = targetSimple + "Emitter";
        String emitterQualified = pkg.isEmpty() ? emitterSimple : pkg + "." + emitterSimple;

        TypeCodec codec = new TypeCodec(processingEnv);
        Messager messager = (kind, msg, el) -> processingEnv.getMessager().printMessage(kind, msg, el);
        List<EmittedEvent> events = methods.stream().map(m -> EmittedEvent.of(m, messager)).toList();

        StringBuilder methodImpls = new StringBuilder();
        for (EmittedEvent ev : events) {
            methodImpls.append(generateOneEmit(ev, codec));
        }

        StringBuilder src = new StringBuilder();
        if (!pkg.isEmpty()) {
            src.append("package ").append(pkg).append(";\n\n");
        }
        src.append("/** Generated by sugr's @Emits annotation processor from ")
                .append(targetSimple).append(". Do not edit by hand. */\n");
        src.append("public final class ").append(emitterSimple).append(" implements ").append(targetSimple).append(" {\n\n");
        src.append("    private final com.sugr.core.Window window;\n\n");
        src.append("    public ").append(emitterSimple).append("(com.sugr.core.Window window) {\n");
        src.append("        this.window = window;\n    }\n\n");
        src.append(methodImpls);
        for (String helper : codec.helperMethodsSource()) {
            src.append("    ").append(helper.replace("\n", "\n    ")).append("\n\n");
        }
        src.append("}\n");

        try {
            JavaFileObject file = processingEnv.getFiler().createSourceFile(emitterQualified, target);
            try (Writer w = file.openWriter()) {
                w.write(src.toString());
            }
        } catch (IOException e) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                    "Failed to write " + emitterQualified + ": " + e, target);
        }

        generateTsStub(pkg, targetSimple, events, codec);
    }

    private String generateOneEmit(EmittedEvent ev, TypeCodec codec) {
        StringBuilder m = new StringBuilder();
        if (ev.payload() == null) {
            m.append("    @Override\n    public void ").append(ev.javaMethodName()).append("() {\n");
            m.append("        window.emit(\"").append(ev.jsName()).append("\", \"null\");\n");
        } else {
            VariableElement p = ev.payload();
            m.append("    @Override\n    public void ").append(ev.javaMethodName()).append('(')
                    .append(codec.javaTypeName(p.asType())).append(' ').append(p.getSimpleName()).append(") {\n");
            m.append("        window.emit(\"").append(ev.jsName()).append("\", ")
                    .append(codec.encode(p.asType(), p.getSimpleName().toString())).append(".encode());\n");
        }
        m.append("    }\n\n");
        return m.toString();
    }

    private void generateTsStub(String pkg, String targetSimple, List<EmittedEvent> events, TypeCodec codec) {
        StringBuilder methodsTs = new StringBuilder();
        for (EmittedEvent ev : events) {
            String onName = "on" + Character.toUpperCase(ev.jsName().charAt(0)) + ev.jsName().substring(1);
            boolean hasPayload = ev.payload() != null;
            String tsPayload = hasPayload ? codec.tsType(ev.payload().asType()) : "void";
            String listenerType = hasPayload ? "(payload: " + tsPayload + ") => void" : "() => void";

            methodsTs.append("  ").append(onName).append("(listener: ").append(listenerType)
                    .append("): () => void {\n");
            methodsTs.append("    events.on<").append(tsPayload.equals("void") ? "null" : tsPayload)
                    .append(">('").append(ev.jsName()).append("', listener)\n");
            methodsTs.append("    return () => events.off('").append(ev.jsName()).append("', listener)\n");
            methodsTs.append("  },\n");
        }

        StringBuilder ts = new StringBuilder();
        ts.append("// AUTO-GENERATED by sugr's @Emits annotation processor from ").append(targetSimple).append(". Do not edit by hand.\n");
        ts.append("import { events } from '@sugr/runtime'\n\n");
        for (String iface : codec.tsInterfaceSource().values()) {
            ts.append(iface).append("\n\n");
        }
        ts.append("export const ").append(targetSimple).append(" = {\n").append(methodsTs).append("}\n");

        try {
            String relativeName = targetSimple + ".generated.ts";
            FileObject file = processingEnv.getFiler().createResource(StandardLocation.SOURCE_OUTPUT, pkg, relativeName);
            try (Writer w = file.openWriter()) {
                w.write(ts.toString());
            }
        } catch (IOException e) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, "Failed to write TS stub: " + e);
        }
    }
}
